name: Get PR Reviewers

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  get-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get CODEOWNERS reviewers
        uses: ./codeowner-reviewers-action
        with:
          custom_message: "Please review these changes as soon as possible."
          codeowners_path: ".github/CODEOWNERS" 