name: Get PR Reviewers

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  get-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get CODEOWNERS reviewers
        uses: Echo-Head-Wall/useful-actions/codeowner-reviewers-action@3eb9868b6456ef475d198911687c1c72a138b59c
        with:
          custom_message: "Please review these changes as soon as possible."
          codeowners_path: ".github/CODEOWNERS"  